version: "3.8"

services:
  function-dev:
    build:
      context: .
      target: dev
    image: lambda-go:latest
    container_name: my_function
    ports:
      - "9000:8080"
    environment:
      AWS_LAMBDA_FUNCTION_TIMEOUT: "15"